<a href="https://colab.research.google.com/github/dpsinghvij/mlpractice/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
myList = [1,2,3]

In [3]:
np.array(myList)

array([1, 2, 3])

In [5]:
np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
 np.linspace(0, 10, 21).reshape(3, 7)

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ],
       [ 3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(3, 4)

array([[0.90657248, 0.8006862 , 0.0750021 , 0.94980029],
       [0.91534292, 0.15825613, 0.61959669, 0.81256142],
       [0.53495793, 0.94644476, 0.16220748, 0.19308355]])

In [13]:
np.random.randn(3, 4)

array([[-0.49091105, -1.17725736,  1.12283396,  0.18219829],
       [ 0.02228697, -2.42534419, -1.22913473, -0.16025829],
       [ 0.84374044, -0.68227521, -0.65990321, -0.24957603]])

In [14]:
np.random.randint(1, 100, (10, 2))

array([[28, 99],
       [92, 84],
       [50, 47],
       [13,  7],
       [29, 72],
       [59, 14],
       [91, 68],
       [90, 98],
       [42, 10],
       [49, 75]])

In [25]:
array2d = np.arange(1, 10).reshape(3, 3)

In [26]:
array2d[array2d > 2]

array([3, 4, 5, 6, 7, 8, 9])